### ISSUE TITLE
problem with @overtire method

### ISSUE THREAD

**Issue by rasel6999** [KonstantinSchubert/request_data_webviewclient#1]
![issu](https://user-images.githubusercontent.com/17203863/34342271-19b3e42a-e9c4-11e7-99d8-3e47cd96d01f.PNG)

sir  can u please cheke this issu?

**Comment by KonstantinSchubert** [comment]
HI,
you are overriding the wrong method. It should be `shouldInterceptRequest`, not `shouldOverrideUrlLoading`.

**Comment by rasel6999** [comment]
![issu](https://user-images.githubusercontent.com/17203863/34352248-51d1536c-e9d6-11e7-8ff8-061bb5061224.PNG)

sir thank u for your replay . i'm also using shouldInterceptRequest method   ..
but this is also error with

"WriteHandlingWebViewClient (WebView) in WriteHandlingWebViewClient cannot be applied to () "
